version: '3.4'

services:
  igs.techtest:
    image: igstechtest/api
    build:
      context: ./IGS.TechTest
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mssqldb
  mssqldb:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "1433:1433"