version: '3.4'

services:
  igs.techtest:
    image: igstechtest/api
    build:
      context: .
      dockerfile: IGS.TechTest/Dockerfile
    ports:
      - "5001:443"
      - "5000:80"
    depends_on:
      - mssqldb
  mssqldb:
    build:
      context: ./db
      dockerfile: Dockerfile